version: '3.5'
services:
  php-base:
    build:
      context: .
    image: mindhochschulnetzwerk/php-base
    restart: always
    ports:
      - "8000:8080"
    volumes:
      - "./index.php:/var/www/html/index.php:ro"
